// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8xSVC2DeSPGcdJslxaHs-whN56ueQ6hA',
    appId: '1:554862548:web:3048695510123d9162f841',
    messagingSenderId: '554862548',
    projectId: 'mellow-mental-health',
    authDomain: 'mellow-mental-health.firebaseapp.com',
    storageBucket: 'mellow-mental-health.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeIT2_kZCh9Zvk-M7edyb-Xg0I2BooNts',
    appId: '1:554862548:android:7644d8dcb1e60c9662f841',
    messagingSenderId: '554862548',
    projectId: 'mellow-mental-health',
    storageBucket: 'mellow-mental-health.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf7vYTIsBUGD9XXTh3zDcul9vSsHeyXE4',
    appId: '1:554862548:ios:e536333f9e8f1b2062f841',
    messagingSenderId: '554862548',
    projectId: 'mellow-mental-health',
    storageBucket: 'mellow-mental-health.firebasestorage.app',
    iosBundleId: 'com.example.mellowapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf7vYTIsBUGD9XXTh3zDcul9vSsHeyXE4',
    appId: '1:554862548:ios:e536333f9e8f1b2062f841',
    messagingSenderId: '554862548',
    projectId: 'mellow-mental-health',
    storageBucket: 'mellow-mental-health.firebasestorage.app',
    iosBundleId: 'com.example.mellowapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8xSVC2DeSPGcdJslxaHs-whN56ueQ6hA',
    appId: '1:554862548:web:cc7f50f3f1d7592f62f841',
    messagingSenderId: '554862548',
    projectId: 'mellow-mental-health',
    authDomain: 'mellow-mental-health.firebaseapp.com',
    storageBucket: 'mellow-mental-health.firebasestorage.app',
  );
}
